# Site
name: "Garagem Educação"
title: "Garagem Educação"
description: "Quem inova em educação lê."
logo: 'assets/images/logo-new.png'
favicon: 'assets/images/logo-new.png'
baseurl: ''
# google_analytics: 'G-7MR48NB7DR'
google_gtag_analytics: G-7MR48NB7DR
# disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  maluta:
    name: Tiago Maluta
    display_name: Tiago Maluta    
    avatar: 'assets/images/avatar-maluta.png'
    gravatar: f615d34c675bc325d78631c8077f0187
    email: tiago.maluta@gmail.com
    web: https://maluta.github.io
    twitter: https://twitter.com/maluta
    description: ""
  amaral: 
    name: Amaral Medeiros
    display_name: Amaral Medeiros    
    avatar: 'assets/images/avatar-amaral.png'
    gravatar: f615d34c675bc325d78631c8077f0187
    email: tiago.maluta@gmail.com
    web: https://amaralmedeiros.com
    twitter: https://twitter.com/amaralmedeiros
    description: "Empreendedor @ ChatClass, acelerada por Google / Facebook e com 400 mil alunos em 🇧🇷 🇩🇪. Co-autor de livro de Stanford sobre ensino de coding, Ex-Líder Transfor. Digital @ Instituto Ayrton Senna"
  raphaelsanto:
      name: Raphael Santo
      display_name: Raphael Santo
      avatar: 'assets/images/avatar-raphaelsanto.png'
      web: https://www.linkedin.com/in/raphael-santo/
      description: "Tecnólogo e graduado em Administração na Ufscar. É coordenador comercial do Marketplace Melhor Escola do Grupo Quero Educação, entusiasta do mundo das vendas e apaixonado pela temática educacional."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: ""
#adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
